POST http://localhost:5000/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzIwMjM3MCwiZXhwIjoxNjAzMjA1OTcwfQ.QUuKWYxjlIq5WLNf-3fb0WraRuMV6wWH9i663xAKxbk
Content-Type: application/json

{
    "name": "Bagus",
    "email": "bagusnug@gmail.com",
    "password": "mendingtidur",
    "role": "distributor"
}

###

POST http://127.0.0.1:4000/api/auth/login
Content-Type: application/json



{
    "email": "ngutang@gmail.com",
    "password": "plangaplongo"
}


###
GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzIwMDk0MywiZXhwIjoxNjAzMjA0NTQzfQ.z6UuP0QOAVGCofVzwRof45KU0sMJqMQONm6ZUl_dtFg

###

GET http://localhost:5000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGJmZGE1NmUyMDJjNDI0NDAwNjkwYSIsImlhdCI6MTYwMzEwODgyMiwiZXhwIjoxNjAzMTEyNDIyfQ.5MYqiWFk1zSFikCvmP3OMbUinSLN-F2VZDYrXL3cmf4
###

POST http://localhost:5000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGJmZGE1NmUyMDJjNDI0NDAwNjkwYSIsImlhdCI6MTYwMzA5MjM3OSwiZXhwIjoxNjAzMDk1OTc5fQ.jQZoXWPuBrLpMQd72aKrQ40sC3i0Qvv1GP0uuUbJP5I
Content-Type: application/json

{
    "productName": "Bawang",
    "unitName": "Gr",
    "categoryName": "Organic Superfood",
    "brandName": "Teuing",
    "stock": 100,
    "het": "Rp. 75.000",
    "price": "Rp. 23.000"
}


###

PUT http://localhost:5000/api/products/5f8d48414a6a434908c7a1e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGJmZGE1NmUyMDJjNDI0NDAwNjkwYSIsImlhdCI6MTYwMzEwODkxMiwiZXhwIjoxNjAzMTEyNTEyfQ.HTEdCMPg6IMUSTWWTbgcMTZAE3HG2XwL7eUCx_6YM7A
Content-Type: application/json

{
    "productName": "Goodday",
    "unitName": "pcs",
    "categoryName": "Coffee",
    "brandName": "Goodday",
    "stock": 1000,
    "het": "Rp. 74.000",
    "price": "Rp. 10.000"
}

###

DELETE http://localhost:5000/api/products/5f8d40aec9882249283600f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGJmZGE1NmUyMDJjNDI0NDAwNjkwYSIsImlhdCI6MTYwMzEwODkxMiwiZXhwIjoxNjAzMTEyNTEyfQ.HTEdCMPg6IMUSTWWTbgcMTZAE3HG2XwL7eUCx_6YM7A


###
GET http://localhost:5000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzE5ODk4NywiZXhwIjoxNjAzMjAyNTg3fQ.-RSuni0sy5POXBzOn2brvdw0oGFOUKTRgEa1EHmR8rk


###
POST http://localhost:5000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzE5ODk4NywiZXhwIjoxNjAzMjAyNTg3fQ.-RSuni0sy5POXBzOn2brvdw0oGFOUKTRgEa1EHmR8rk
Content-Type: application/json

{
    "name": "Setyo Bagus Nugraha",
    "phoneNumber": "+62819282123",
    "address": "Jl. Bangsat no 41",
    "orderVia": "Instagram",
    "shipper": "Nugraha (081281928283)",
    "provinceDestination": "Jawa Barat",
    "cityDestination": "Sukabumi",
    "subdistrictDestination": "Gunung Puyuh",
    "postalCode": "43122",
    "orderStatus": "unverified"
}

###
PUT http://localhost:5000/api/orders/5f8d980dfda95e49109804c1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGJmZGE1NmUyMDJjNDI0NDAwNjkwYSIsImlhdCI6MTYwMzE2ODA5NSwiZXhwIjoxNjAzMTcxNjk1fQ.3oqk0MeMsYJXL85BaPO40FyJWga_GA4UZ4rlthpBBiE
Content-Type: application/json

{
    "name": "Nugraha",
    "phoneNumber": "+62819282123",
    "address": "Jl. Bangsat no 41",
    "orderVia": "Instagram",
    "shipper": "Nugraha (081281928283)",
    "provinceDestination": "Jawa Barat",
    "cityDestination": "Sukabumi",
    "subdistrictDestination": "Gunung",
    "postalCode": "43121"
}

###
DELETE http://localhost:5000/api/orders/5f8d9807fda95e49109804c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzE5ODk4NywiZXhwIjoxNjAzMjAyNTg3fQ.-RSuni0sy5POXBzOn2brvdw0oGFOUKTRgEa1EHmR8rk


###

GET http://localhost:5000/api/banks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzIwMjM3MCwiZXhwIjoxNjAzMjA1OTcwfQ.QUuKWYxjlIq5WLNf-3fb0WraRuMV6wWH9i663xAKxbk


###

POST http://localhost:5000/api/banks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzIwMjM3MCwiZXhwIjoxNjAzMjA1OTcwfQ.QUuKWYxjlIq5WLNf-3fb0WraRuMV6wWH9i663xAKxbk
Content-Type: application/json

{
    "bankAccount": "BRI",
    "accountName": "Setyo Bagus Nugraha",
    "accountNumber": "12312312345"
}

###
DELETE http://localhost:5000/api/banks/5f8eee462440ba41f4d53b4a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOGU3MjUxNTEwZGZiMWMxMGQ1YjkwMiIsImlhdCI6MTYwMzIwMjM3MCwiZXhwIjoxNjAzMjA1OTcwfQ.QUuKWYxjlIq5WLNf-3fb0WraRuMV6wWH9i663xAKxbk